### ISSUE TITLE
notElem docs say True where False would make more sense

### ISSUE THREAD

**Issue by exarkun** [bos/bloomfilter#17]
notElem is documented as:

> Query an immutable Bloom filter for non-membership. If the value is present, return False. If the value is not present, there is still some possibility that True will be returned.

It would make more sense if it said "there is still some possibility that False will be returned." and I suppose the current text is a copy/paste mistake from the `elem` docs.

**Comment by joeyh** [comment]
fixed in 2.0.1.1
