### ISSUE TITLE
"capacity too large to represent" error

### ISSUE THREAD

**Issue by CrowDaddy** [bos/bloomfilter#7]
I seem to get the "capacity too large to represent" error no matter how large or small the bytestring list is, using easyList from Data.BloomFilter.Easy; I even tried using Words.hs from your examples and still got it, with input files ranging from 10 to 10,000 lines.  With an error rate of 0.01, are there bounds on number of words which can be handled?  Am using yyour version 2.0.0.0

**Comment by peti** [comment]
Can this issue be closed? It appears that  44b01ba fixes it, no?

**Comment by joeyh** [comment]
44b01ba is the commit from 2012 that introduced this bug. So, no, can't be closed yet AFAICS.

**Comment by joeyh** [comment]
FWIW, Debian has patched bloomfilter by simply reverting 44b01ba. This seems to work on all architectures supported by debian, both 32 bit and 64 bit.

**Comment by peti** [comment]
Thank you very much for the clarification. I've added an appropriate revert in NixOS, too: https://github.com/NixOS/nixpkgs/commit/2b71e4643e33c427c26efc16b69765170b292cca.

**Comment by CrowDaddy** [comment]
I used stack recently to install bloomfilter on a 32-bit Ubuntu VM, and sure enough, it got the same execution error; if we want stack to offer an 'it just works' environment this should be fixed in Stackage. 

----- Original Message -----

**Comment by joeyh** [comment]
Fixed this in 2.0.1.2
